# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6dc5f28e334ce9f112eb18de563e58cb884d688d0ea64b702c709c88a0705943aed6af241080bf60b6ba85baf46bb6186cd45de90816b59a52e05d1685c7606

test:
  secret_key_base: e3406bcd07de246188cbfe6a15b5c707754db79e78e225d31b70abb15f9ba56b5fcd3fc1d923f22c79779c6b5b907b7aaf60b5304adc49d11eb77e2bb665876e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 5e6b6d2bd7bf26d02679ac958b520adf41b211eb0b8f33742abc5437711d0ad314baf13efc0d35d7568d2e469668a7021cf5e945c667bd16507777aedb770f83
